"""Doxyfile fragment generation.

@brief Emit the Doxyfile settings that make this tool's dialect valid doxygen.
@version 1.0

doxygen-guard invents tags (@req and the exemption markers) that doxygen does not
define, so doxygen emits unknown-command warnings on files written to satisfy the gate.
Declaring them as ALIASES makes them real doxygen commands, which is the supported
extension mechanism.

This module is pure Python emitting text. Doxygen is NOT a runtime dependency of
doxygen-guard, and never becomes one — the fragment is something you include in your own
Doxyfile. Doxygen's role is as an authority on doxygen validity, exercised in CI, not as
part of the pre-commit gate.
"""

from __future__ import annotations

import logging
from typing import Any

from .checks import EXEMPTION_TAGS, TOOL_OWNED_TAGS
from .config import get_validate

logger = logging.getLogger(__name__)

# Human-readable section titles for tags whose name does not title-case well.
_TAG_TITLES = {"req": "Requirement"}

_HEADER = """\
# Generated by `doxygen-guard doxyfile`. Include from your own Doxyfile:
#
#     @INCLUDE = doxygen-guard.doxyfile
#
# Regenerate after changing validate.tags or validate.version.tag.
"""

# Only settings that check *validity* — whether the comment is well-formed doxygen.
#
# WARN_IF_UNDOCUMENTED and WARN_NO_PARAMDOC are deliberately NOT enabled here. They are
# policy, not validity, and they enforce a stricter standard than this tool: measured
# against doxygen-guard's own source they produce 399 warnings, 309 of them
# WARN_NO_PARAMDOC demanding @param for every parameter and the rest flagging
# module-level variables. doxygen-guard requires neither. Turning them on by default
# would impose doxygen's policy on adopters, which inverts the division of authority —
# doxygen decides what is valid doxygen, this tool decides what satisfies team policy.
# They are listed as commented opt-ins instead.
_WARNINGS = (("WARN_IF_DOC_ERROR", "YES", "malformed doxygen markup"),)

_OPTIONAL_WARNINGS = (
    ("WARN_IF_UNDOCUMENTED", "flags undocumented members, including module variables"),
    ("WARN_NO_PARAMDOC", "requires @param for every parameter and @return on non-void"),
)


## @brief Render one ALIASES line for a marker tag that carries no value.
#  @version 1.0
#  @dg_internal
#  @return A Doxyfile ALIASES assignment mapping the tag to nothing
def _marker_alias(tag: str) -> str:
    return f'ALIASES += "{tag}="'


## @brief Render one ALIASES line for a tag whose value should be cross-referenced.
#  @version 1.0
#  @dg_internal
#  @return A Doxyfile ALIASES assignment defining an xrefitem section
def _xref_alias(tag: str, title: str, page: str) -> str:
    return f'ALIASES += "{tag}=\\xrefitem {tag} \\"{title}\\" \\"{page}\\""'


## @brief Collect the tool-owned tags that need declaring for a given config.
#  @details Includes a non-default validate.version.tag: pointing the revision counter
#  at a custom tag means doxygen does not know that one either.
#  @version 1.0
#  @req REQ-DDB-GUARD-017
#  @return Sorted tag names, without the leading at-sign
def tool_tags_for(config: dict[str, Any]) -> list[str]:
    validate = get_validate(config)
    tags = set(TOOL_OWNED_TAGS)
    tags.update(validate.get("tags", {}).keys())
    tags.update(str(t).lstrip("@") for t in validate.get("extra_tags", []))

    version_tag = str(validate.get("version", {}).get("tag", "@version")).lstrip("@")
    if version_tag != "version":
        tags.add(version_tag)
    # brief/version/return and friends are real doxygen commands; never alias those.
    return sorted(tags - {"brief", "version", "return", "returns", "file", "param"})


## @brief Build the Doxyfile fragment for the given config.
#  @version 1.0
#  @req REQ-DDB-GUARD-017
#  @return Doxyfile text declaring ALIASES and the mirroring warning settings
def build_fragment(config: dict[str, Any]) -> str:
    lines = [_HEADER, "# Tags doxygen-guard defines that doxygen does not."]

    for tag in tool_tags_for(config):
        if tag in EXEMPTION_TAGS:
            lines.append(f"# @{tag}: exemption marker, no rendered output")
            lines.append(_marker_alias(tag))
        else:
            title = _TAG_TITLES.get(tag, tag.replace("_", " ").title())
            lines.append(_xref_alias(tag, title, f"{title} Index"))

    lines.append("")
    lines.append("# Validity: is the comment well-formed doxygen.")
    for key, value, why in _WARNINGS:
        lines.append(f"# {why}")
        lines.append(f"{key} = {value}")

    lines.append("")
    lines.append("# Policy, not validity — stricter than doxygen-guard. Opt in if you want it.")
    for key, why in _OPTIONAL_WARNINGS:
        lines.append(f"# {key} = YES   # {why}")

    lines.append("")
    lines.append("# Exemption markers must not hide the rest of the block.")
    lines.append("INTERNAL_DOCS = YES")

    logger.info("Generated Doxyfile fragment for %d tool-owned tag(s)", len(tool_tags_for(config)))
    return "\n".join(lines) + "\n"
